### ISSUE TITLE
MEF library under windows - invalid pointer, application crashes 

### ISSUE THREAD

**Issue by vkremen** [msel-source/meflib#1]
Hello,
we have identified another issue with the MEF library today.

When we want to read a source file without time series data(i.e. we want to read only the file headers), then the returned data structure from read_MEF_session function from meflib.c has an invalid pointer to RED_blocks.

Screenshot of a SESSION structure as visualized by a debugger is attached.
![screenshot of session structure by debugger](https://user-images.githubusercontent.com/21159687/51063878-89b9ba80-15c2-11e9-9f5c-fa438dd91aa1.png)

When we try to access SESSION structure from C#, it fails. C# treats NULL pointers correctly however when there is a nonzero address in the pointer, C# tries to access the memory and read it as a structure. In this case (only header read, no data behind it) it causes an invalid operation - access to a memory this process does not “own”. The operating system kills it instantly.

The root cause is this line of code:
data_ptr = (ui1 *)fps->raw_data + UNIVERSAL_HEADER_BYTES;

when fps->raw_data is NULL (i.e. no data was read) address 0 + 1024 is assigned into data_ptr. Then data_ptr is assigned to RED_blocks.

I propose a fix, in this case replacing the line with:

if (NULL != fps->raw_data)

{

       data_ptr = (ui1 *)fps->raw_data + UNIVERSAL_HEADER_BYTES;

}
and initializing data_ptr to NULL.

This keeps NULL in data_ptr (if initialized) and therefore NULL is assigned to RED_blocks correctly as it should be.

This line of code appears 3 times in meflib.c. Modified meflib.c is attached as well as a diff file from our versioning system.
[diff and meflib.zip](https://github.com/msel-source/meflib/files/2751399/diff.and.meflib.zip)

**Comment by cimbi** [comment]
Fixed by commit 27fc206825674ee9c449161646cf22c3d83a4130
