### ISSUE TITLE
Incorrect/different 'earliest_start_time' and 'latest_end_time' in Windows

### ISSUE THREAD

**Issue by MaxvandenBoom** [msel-source/meflib#11]
Hi Dan,

I found another windows(-only) bug in the library which results in incorrect (or different from mac) values in the session's 'earliest_start_time' and 'latest_end_time' variables.

In your library for a channel there is:
```
#ifdef _WIN32
    channel->earliest_start_time = LLONG_MAX;
    channel->latest_end_time = LLONG_MIN;
#else
    channel->earliest_start_time = LONG_MAX;
    channel->latest_end_time = LONG_MIN;
#endif
```
whereas for a session (around line 6000) there is no precompiler ifdef and LONG_ is used in windows.

The pull request should fix it. I corrected it in the same way as you did with the channel object.

Best regards,
Max

**Comment by cimbi** [comment]
Resolved by #10
