### ISSUE TITLE
Reference to uninitialized local pointer variable in video channels

### ISSUE THREAD

**Issue by MaxvandenBoom** [msel-source/meflib#14]
Hi Jan and Dan,

I encountered this issue upon compiling the meflib in VS2015. It applies only to the reading of video channels.

In the `read_MEF_channel` function (`meflib.c`) there is a reference to a variable which is uninitialized:
`bzero(ctmd->protected_region, METADATA_SECTION_3_PROTECTED_REGION_BYTES);` (on line 5570)

Given the MEF 3 specification, the context (lines above and below) and the way it is done for the time-series channels, this should be:
`bzero(cmd3->protected_region, METADATA_SECTION_3_PROTECTED_REGION_BYTES);`
\
\
The exact same thing happens again for video-channels later on:
`bzero(stmd->protected_region, METADATA_SECTION_3_PROTECTED_REGION_BYTES);` (on line 6268)
which should be:
`bzero(smd3->protected_region, METADATA_SECTION_3_PROTECTED_REGION_BYTES);`
\
\
I might have another issue later, so I will combine them in one pull request to make it easy.

Best regards,
Max

**Comment by cimbi** [comment]
Sounds good and thanks for spotting the bug. It is weird though. I did not have this bug in my local branch and git seemed not to notice the difference.

**Comment by MaxvandenBoom** [comment]
That is quite weird of git. Happy to help :)

**Comment by cimbi** [comment]
Fixed by PR #16
