### ISSUE TITLE
Tiny memoryleak in 'generate_file_list' in windows

### ISSUE THREAD

**Issue by MaxvandenBoom** [msel-source/meflib#15]
Hi Jan and Dan,

I was tracing memory leaks, and by chance found a tiny one in 'generate_file_list'.

Within the `generate_file_list`, the windows functions `FindFirstFile` and `FindNextFile` are called which reserve memory, accessible using the handle `hFind`. The function `FindClose` has to be called to release the memory.

You use the `FindFirstFile` and `FindNextFile` functions twice, first to make an inventory of the MEF3 files (line 4013 to 4036), then a second time to copy the filepaths (line 4039 to 4096). After the second time, there is indeed a call to `FindClose` (line 4099). However there is no 'FindClose' between the first and second time, causing `hFind` to be overwritten and the memory never to be freed.

It is easily solved by adding:
`FindClose(hFind);`
around line 4037, which is after the first round of `FindFirstFile` and `FindNextFile` use.

I will add it to a pull request.

Best, Max

**Comment by cimbi** [comment]
Great Max, thanks for helping with finding bugs on windows. Dan and I use UNIX systems so we might miss these

**Comment by cimbi** [comment]
Fixed by PR #16
