### ISSUE TITLE
MEFLIB locks the files when read in process under MS Windows

### ISSUE THREAD

**Issue by vkremen** [msel-source/meflib#18]
It looks like meflib is locking the files when being read and didn't release the lock after the data are read. Thus files can't be manipulated in OS or by any other program. For example moved, deleted, appended etc. This was tested also in Python pymef. When the parent process that calls the meflib is closed (e.g. Python) then the lock is cleared. 

Can you investigate that and fix it. Thanks.

**Comment by cimbi** [comment]
Cau Vasku,
things that would help me investigate the problem - OS (linux/win/mac), if tested with pymef then pymef version. Have you seen this outside of pymef? I think I know where the problem might be but give me those answers first please. cheers

**Comment by vkremen** [comment]
Yep,

we call it from C# as well using same meflib under Windows. Same as newest pymef. Unless C# binary or Python is closed, the data can't be moved. I am guessing it will be similar in Pymefview, but haven't tried it.


- Vaclav

 ​

Vaclav Kremen, M.Sc.Eng., Ph.D.

________________________________________________________________

Associate Professor of Biomedical Engineering, Principal Engineer

@ Bioelectronics Neurophysiology and Engineering Lab  <https://www.mayo.edu/research/labs/bioelectronics-neurophysiology-engineering/overview>   |  Dept. of Neurology

Phone: (507) 538-5698  |  Pager: 127-09723  |  Email: kremen.vaclav@mayo.edu<mailto:kremen.vaclav@mayo.edu>

ORCID: https://orcid.org/0000-0001-9844-7617

________________________________________________________________

Mayo Clinic  |  200 First Street SW, Rochester, MN 55905  |  www.mayoclinic.org<http://www.mayoclinic.org/>


________________________________

**Comment by cimbi** [comment]
file locking is definitely disabled for win. I think the problem lies somewhere else. pymef keeps the file pointers open for multiple reads and the OS prevents you from modifying the files (which would be a correct behavior). The solutions:

1) when using pymef, make sure you call MefSession.close() once you are done reading
2) from C# make sure that: fps->directives.close_file == MEF_TRUE when reading and/or freeing file_processing_struct, alternatively call fps_close(fps)

I'll test with pymef and get back to you with the results

**Comment by vkremen** [comment]
Thanks Jan, we will test it.

Can we modify Help/Manual with correct examples on this?

Regards,


- Vaclav

 ​

Vaclav Kremen, M.Sc.Eng., Ph.D.

________________________________________________________________

Associate Professor of Biomedical Engineering, Principal Engineer

@ Bioelectronics Neurophysiology and Engineering Lab  <https://www.mayo.edu/research/labs/bioelectronics-neurophysiology-engineering/overview>   |  Dept. of Neurology

Phone: (507) 538-5698  |  Pager: 127-09723  |  Email: kremen.vaclav@mayo.edu<mailto:kremen.vaclav@mayo.edu>

ORCID: https://orcid.org/0000-0001-9844-7617

________________________________________________________________

Mayo Clinic  |  200 First Street SW, Rochester, MN 55905  |  www.mayoclinic.org<http://www.mayoclinic.org/>


________________________________

**Comment by cimbi** [comment]
I've just tested with pymef on linux and I can move the session .mefd folder without any problems. The pymef's MefSession can not read after that obviously. I have no windows machine to test this on. But let me know if the suggested solutions worked. I'll leave the issue open till then.

**Comment by MaxvandenBoom** [comment]
Hi guys,

I don't know if this is relevant, but I vaguely remember having some trouble with the file-locking mechanism in the past.
It occured when using a mac computer (which uses the mac part of the code) on a path that leads to a windows file server (which Mayo uses) that does not support file-locking; it made meflib crash.

I understand this is a different problem with mac file-locking and not unlocking, but I wonder if that, whole mechanism and considering cross OS uses, is worth the trouble. Shouldn't the read/write mode in the `fopen` call already take care of that.

**Comment by dancrepeau** [comment]
File locking had been previously #ifdef'd out for Windows, and now it is commented out in all cases.  File locking in general was causing intermittent problems, and through conversation, none of us could think of a compelling reason to keep those calls in the code base.
