### ISSUE TITLE
file_length in Win32

### ISSUE THREAD

**Issue by dancrepeau** [msel-source/meflib#21]
It seems the meflib is broken in Win32 when it encounters data file sizes larger than ~4 GB.  It is currently using _stat() and fstat() to determine file sizes, but testing shows it returns file size of 0 in cases where it is really greater than 4 GB.  Replacing these callis with _stat64() seems to fix the problem.  This issue occurs in 3 places: fps_open, fps_close, and generate_file_list.  Unless there is an objection I will finish testing and push the change up to github.

**Comment by dancrepeau** [comment]
No reason I can think of not to push these changes to github.  meflib.c has been updated.

**Comment by vkremen** [comment]
Excellent! Thanks much!


- Vaclav

 ​

Vaclav Kremen, M.Sc.Eng., Ph.D.

________________________________________________________________

Associate Professor of Biomedical Engineering, Principal Engineer

@ Bioelectronics Neurophysiology and Engineering Lab  <https://www.mayo.edu/research/labs/bioelectronics-neurophysiology-engineering/overview>   |  Dept. of Neurology

Phone: (507) 538-5698  |  Pager: 127-09723  |  Email: kremen.vaclav@mayo.edu<mailto:kremen.vaclav@mayo.edu>

ORCID: https://orcid.org/0000-0001-9844-7617

________________________________________________________________

Mayo Clinic  |  200 First Street SW, Rochester, MN 55905  |  www.mayoclinic.org<http://www.mayoclinic.org/>


________________________________
