### ISSUE TITLE
compiling under linux/Ubuntu

### ISSUE THREAD

**Issue by dancrepeau** [msel-source/meflib#27]
When compiling under Ubuntu 18.04.5, I found I needed to change
#include <sys/time.h>
to simply
#include <time.h>
in meflib.h.  Previously I have done most Mac OS compiles.  Without the change, line 4596 of meflib.c generates an error: "struct tm time_info;", "error: storage size of 'time_info' isn't known".

If anyone has expertise in how to properly handle this situation, so that changes to the file don't need to be made when changing OS's, that would be great.

**Comment by MaxvandenBoom** [comment]
Haha, only read this just now, check pull request https://github.com/msel-source/meflib/pull/28 :)

For Mac either `<sys/time.h>` **or** `<time.h>` needs to be included or it won't work. Just `<time.h>` is also fine. Or you can have both (`<sys/time.h>` and `<time.h>`, like in https://github.com/msel-source/meflib/pull/28) just to be sure, it will compile fine on both OSs, I've tried.

**Comment by dancrepeau** [comment]
Looks like this one should be closed out, as Max merged the new line into meflib.h.  Thanks!
