### ISSUE TITLE
generate_file_list handles paths containing whitespace incorrectly

### ISSUE THREAD

**Issue by jfromme** [msel-source/meflib#4]
When generate_file_list is passed an enclosing_directory which contains whitespace the resulting file_list is incorrect because the `fscanf` call on the results of the `ls -1d` parses those results incorrectly.

For example, calling generate_file_list with an enclosing_directory of 

`/Volumes/Case Sensitive Git Partition/git/mef3-project/target/test-classes/left_central-ref.timd`

which contains a single segment, `Left_Central-Ref-000000.segd`, results in an incorrect four element file_list:

`file_list[0] = /Volumes/Case`
`file_list[1] = Sensitive`
`file_list[2] = Git`
`file_list[3] = Partition/git/mef3-project/target/test-classes/left_central-ref.timd\Left_Central-Ref-000000.segd`

**Comment by cimbi** [comment]
On UNIX systems this issue is solved by 01add4988a19bfb8f46408c79d0c6f7714bd050d

**Comment by cimbi** [comment]
On Windows this issue is solved by ee904edf3daf4d35909bf8a516f13f9c32636eff
