### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by cimbi** [msel-source/meflib#8]
When opening large sessions with lots of channels and segments the soft limit for number of opened channels is reached.

**Comment by cimbi** [comment]
https://github.com/msel-source/meflib/blob/4f8f0cba71750078e867dd74a7e29cefb7075b3e/meflib/meflib.c#L5917

this line is to blame

**Comment by cimbi** [comment]
The line above is definitely the reason. I could comment it out but that can potentially break codes downstream. It breaks pymef which I can fix but not sure about all the other applications. Not sure how to handle this. Any ideas @dancrepeau, @benbrinkmann ?

**Comment by benbrinkmann** [comment]
Seems like it needs to be fixed, and the proposal of downstream code checking seems more modular. But of course as you mention possible this will break other things. Do you know if there's a way to get an alert when the soft limit is reached? Probably OS dependent and challenging.

**Comment by cimbi** [comment]
I've seen two scenarios on linux - either the error message is displayed but the code continues or a segfault occurs. The segfault is caused by pymef setting to ignore errors. I can reactivate it. That way the user would know at least the system error number but would be unable to fix it unless he/she is a power user and can fix C code.

I haven't seen this on Mac, likely because the default limit is higher. I haven't tested on windows.

**Comment by cimbi** [comment]
OK, I included the changes in f6228685db5552230c5f878029c534c1daea3a17.
